1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

2. Create a random tensor with shape (7, 7).

In [4]:
import torch
x = torch.rand(size = (7 ,7))
print(x)

tensor([[0.5675, 0.9096, 0.8838, 0.7958, 0.8475, 0.9309, 0.4042],
        [0.2093, 0.1325, 0.9084, 0.6996, 0.1128, 0.3802, 0.7406],
        [0.4413, 0.0889, 0.3232, 0.8807, 0.5000, 0.8574, 0.1887],
        [0.9633, 0.0477, 0.0092, 0.8045, 0.8592, 0.6531, 0.5295],
        [0.7795, 0.4039, 0.4073, 0.0878, 0.8474, 0.2499, 0.6306],
        [0.1709, 0.9182, 0.1229, 0.5703, 0.1098, 0.5061, 0.7737],
        [0.1447, 0.8302, 0.2007, 0.5294, 0.6869, 0.9426, 0.6196]])


3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [20]:
y = torch.rand(size = (1, 7))
mul = torch.mm(x, y.T)
print(mul)


tensor([[2.3000],
        [1.4297],
        [1.5608],
        [1.6378],
        [1.3173],
        [1.3216],
        [1.9008]])
tensor([[0.0200, 0.0320, 0.0311, 0.0280, 0.0298, 0.0328, 0.0142],
        [0.0435, 0.0275, 0.1888, 0.1454, 0.0235, 0.0790, 0.1539],
        [0.1832, 0.0369, 0.1342, 0.3656, 0.2076, 0.3560, 0.0784],
        [0.3978, 0.0197, 0.0038, 0.3322, 0.3548, 0.2697, 0.2187],
        [0.4518, 0.2340, 0.2360, 0.0509, 0.4911, 0.1448, 0.3655],
        [0.1281, 0.6882, 0.0921, 0.4275, 0.0823, 0.3793, 0.5799],
        [0.0739, 0.4240, 0.1025, 0.2704, 0.3509, 0.4815, 0.3165]])


4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [145]:
import random
# random.seed(0) # this is not working
# torch.manual_seed(10) # this is working for cpu and gpu both
torch.cuda.manual_seed(1234) # this is to get reproducible results when using random generation on the GPU
x = torch.rand(7,7, device = "cuda")
print(x)


y = torch.rand(1,7, device = "cuda")
print(y)

mul = torch.mm(x, y.T)
print(mul)


tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255, 0.1114, 0.6812, 0.3608, 0.1715]],
       device='cuda:0')
tensor([[0.9558],
        [1.2227],
        [0.9335],
        [1.6030],
        [0.9344],
        [0.5282],
        [0.5664]], device='cuda:0')


5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [159]:
torch.manual_seed(1234)
x = torch.rand(size = (2,3), device="cuda")
y = torch.rand(size = (2,3), device = "cuda")

print(x, y)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [167]:
mul = torch.mm(x, y.T)
print(mul)


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


8. Find the maximum and minimum values of the output of 7.

In [169]:

print(f"Maximum is: {torch.max(mul)}")
print(f"Maximum is: {mul.max()}")

print(f"Minimum is: {torch.min(mul)}")
print(f"Minimum is: {mul.min()}")

Maximum is: 0.7667766809463501
Maximum is: 0.7667766809463501
Minimum is: 0.27863210439682007
Minimum is: 0.27863210439682007


9. Find the maximum and minimum index values of the output of 7.

In [170]:
print(f"Index of Maximum({torch.max(mul)}): {torch.argmax(mul)}")
print(f"Index of Maximum({mul.max()}: {mul.argmax()}")

print(f"Index of Minimum({torch.min(mul)}): {torch.argmin(mul)}")
print(f"Index of Minimum({mul.min()}): {mul.argmin()}")

Index of Maximum(0.7667766809463501): 1
Index of Maximum(0.7667766809463501: 1
Index of Minimum(0.27863210439682007): 0
Index of Minimum(0.27863210439682007): 0


10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [173]:
t = torch.rand(size = (1,1,1,10))
print(f"Before squeezing : {t.shape}")
print(f"Before squeezing tensor: {t}")
t_squeezed = t.squeeze()
print(f"After squeezing : {t_squeezed.shape}")
print()

Before squeezing : torch.Size([1, 1, 1, 10])
After squeezing : torch.Size([10])
